require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - vendor/**/*
    - tmp/**/*
    - node_modules/**/*
    - db/schema.rb

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

RSpec/BeforeAfterAll:
  Exclude:
    - spec/spec/support/config/ffaker.rb
